#ifndef INCLUDED_COSUPPORT_SMX_ID_MANAGER
#define INCLUDED_COSUPPORT_SMX_ID_MANAGER

#include "xerces_support.hpp"
#include "string_convert.hpp"
#include "string_hash.hpp"

#include <set>
#include <map>
#include <limits>

#include <sysc/kernel/sc_object.h>

namespace CoSupport {

/// @brief Identifier for elements
typedef uint32_t SMXId;

/**
 * @brief Helper struct for (de)serializing Ids
 */
struct SMXIdSer {
  /// @brief Constructor
  SMXIdSer(SMXId id);

  /// @brief Returns Id
  operator SMXId() const;

  /// @brief The Id
  SMXId id;
};


/// @brief Converts Id to string
template<>
std::string asStr<SMXIdSer>(const SMXIdSer& id);

/// @brief Converts string to Id
template<>
SMXIdSer strAs<SMXIdSer>(const std::string &s);


class SMXIdManager {
public:
  /// @brief Returns single instance of SMXIdManager
  static SMXIdManager& getInstance();

  /// @brief Add node with autogenerated Id
  SMXId addNode(Xerces::XN::DOMNode *n);

  /// @brief Add node with Id
  void addNode(Xerces::XN::DOMNode *n, SMXId id);

  /// @brief Delete node
  void delNode(Xerces::XN::DOMNode* n);

  /// @brief Delete node with the specified id
  void delNode(Xerces::XN::DOMNode* n, SMXId id);
  
  /// @brief Lookup node by Id
  Xerces::XN::DOMNode* getNode(SMXId id) const;

  /// @brief Add reference to Id
  SMXId addNRef(Xerces::XN::DOMAttr* n);

  /// @brief Add reference to Id
  void addNRef(Xerces::XN::DOMAttr* n, SMXId id);

  /// @brief Delete reference
  void delNRef(Xerces::XN::DOMAttr* n);

  /// @brief Delete reference with the specified id
  void delNRef(Xerces::XN::DOMAttr* n, SMXId id);
  
  /// @brief Nodes which reference an Id
  typedef std::set<Xerces::XN::DOMAttr*> NRef;

  /// @brief Lookup referencing nodes by Id
  const NRef* getNRef(SMXId id) const;
  
  /// @brief Analyze node (recursive)
  void analyze(Xerces::XN::DOMNode *n);

  /// @brief Convenience typedef
  typedef sc_core::sc_object SCObj;

  /// @brief Add object with autogenerated Id
  SMXId addObj(SCObj* obj, size_t index = 0);

  /// @brief Add object with Id
  void addObj(SCObj* obj, SMXId id, size_t index);

  void delObj(const SCObj* obj);


private:
  
  /// @brief Invisible default constructor
  SMXIdManager();

  /// @brief Disabled copy constructor
  SMXIdManager(const SMXIdManager&);

  /// @brief Disabled assign operator
  SMXIdManager& operator=(const SMXIdManager&);
  
  /// @brief Number of bits in Id type (>= 3)
  static const size_t bits = std::numeric_limits<SMXId>::digits;

  /// @brief Offset for generated Ids
  static const SMXId offGen = 0 << (bits - 2);
  
  /// @brief Offset for named Ids
  static const SMXId offNam = 1 << (bits - 2);

  /// @brief Offset for anonymous Ids
  static const SMXId offAno = 2 << (bits - 2);
  
  /// @brief Offset for reserved index range
  static const SMXId offRes = 3 << (bits - 2);
  
  /// @brief Top Id for generated objects
  SMXId topGen;
  
  /// @brief Top Id for anonymous objects
  SMXId topAno;

  /// @brief Ids for named objects
  std::set<SMXId> setNam;
  
  /// @brief Hash function used for generating Ids for named objects
  FNV<bits - 2> hashNam;

  /// @brief Value type of ObjMap
  typedef std::map<size_t, SMXId> ObjMapEntry;
  
  /// @brief Maps a SystemC object to its Ids
  typedef std::map<SCObj*, ObjMapEntry> ObjMap;
  
  /// @brief Object -> Id lookup map
  ObjMap objMap;

  /// @brief Value type of IdMap
  struct IdMapEntry {
    /// @brief Node defining the Id
    Xerces::XN::DOMNode* node;
    
    /// @brief Attribute nodes referencing the Id
    NRef nref;

    /// @brief Corresponding SystemC object
    SCObj* obj;

    /// @brief Default constructor
    IdMapEntry();
  };


  /// @brief Maps a specific Id to its node
  typedef std::map<SMXId, IdMapEntry> IdMap;

  /// @brief Id -> object lookup map
  IdMap idMap;


  
  
  
  SMXId getUnusedId() const;
};

} // namespace CoSupport

#endif // INCLUDED_COSUPPORT_SMX_ID_MANAGER
